---
- hosts: all
  become: yes

  tasks:
    - name: Remove HTTPD via YUM
      yum: 
        name: httpd
        state: absent
    - name: Remove PHP via YUM
      yum: 
        name: php 
        state: absent
    - name: Delete PHP file from /var/www/html
      file: 
        path: /var/www/html/index.php
        state: absent

