---
- hosts: all
  become: yes

  tasks:
    - yum: 
        name: httpd
        state: latest
    - service: 
        name: httpd
        state: started
    - lineinfile: 
        dest: /etc/httpd/conf/httpd.conf
        regexp: "^Listen"
        line: "Listen 0.0.0.0:80"
        state: present
        backrefs: yes
    - yum: 
        name: php 
        state: latest
    - service: 
        name: httpd
        state: restarted
    - copy: 
        src: index.php
        dest: /var/www/html

