---
- hosts: all
  become: yes

  tasks:
    - name: Create user "{{ user }}"
      user: 
        name: "{{ user }}"
        password: "{{ password }}"
        groups: "{{ group }}"
        createhome: yes
